//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangya_MessengerServer.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_User_Equip
    {
        public int UID { get; set; }
        public Nullable<int> CHARACTER_ID { get; set; }
        public Nullable<int> CLUB_ID { get; set; }
        public Nullable<int> BALL_ID { get; set; }
        public Nullable<int> MASCOT_ID { get; set; }
        public Nullable<int> CADDIE { get; set; }
        public Nullable<int> TITLE_TYPEID { get; set; }
        public Nullable<int> ITEM_SLOT_1 { get; set; }
        public Nullable<int> ITEM_SLOT_2 { get; set; }
        public Nullable<int> ITEM_SLOT_3 { get; set; }
        public Nullable<int> ITEM_SLOT_4 { get; set; }
        public Nullable<int> ITEM_SLOT_5 { get; set; }
        public Nullable<int> ITEM_SLOT_6 { get; set; }
        public Nullable<int> ITEM_SLOT_7 { get; set; }
        public Nullable<int> ITEM_SLOT_8 { get; set; }
        public Nullable<int> ITEM_SLOT_9 { get; set; }
        public Nullable<int> ITEM_SLOT_10 { get; set; }
        public Nullable<int> POSTER_1 { get; set; }
        public Nullable<int> POSTER_2 { get; set; }
    }
}
