//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangya_MessengerServer.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Character
    {
        public int CID { get; set; }
        public int UID { get; set; }
        public int TYPEID { get; set; }
        public Nullable<byte> GIFT_FLAG { get; set; }
        public Nullable<byte> HAIR_COLOR { get; set; }
        public Nullable<byte> POWER { get; set; }
        public Nullable<byte> CONTROL { get; set; }
        public Nullable<byte> IMPACT { get; set; }
        public Nullable<byte> SPIN { get; set; }
        public Nullable<byte> CURVE { get; set; }
        public Nullable<int> CUTIN { get; set; }
    }
}
