//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangya_MessengerServer.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pangya_Character_Equip
    {
        public int EQUIP_IDX { get; set; }
        public int UID { get; set; }
        public int CHAR_IDX { get; set; }
        public Nullable<int> PART_TYPEID_1 { get; set; }
        public Nullable<int> PART_TYPEID_2 { get; set; }
        public Nullable<int> PART_TYPEID_3 { get; set; }
        public Nullable<int> PART_TYPEID_4 { get; set; }
        public Nullable<int> PART_TYPEID_5 { get; set; }
        public Nullable<int> PART_TYPEID_6 { get; set; }
        public Nullable<int> PART_TYPEID_7 { get; set; }
        public Nullable<int> PART_TYPEID_8 { get; set; }
        public Nullable<int> PART_TYPEID_9 { get; set; }
        public Nullable<int> PART_TYPEID_10 { get; set; }
        public Nullable<int> PART_TYPEID_11 { get; set; }
        public Nullable<int> PART_TYPEID_12 { get; set; }
        public Nullable<int> PART_TYPEID_13 { get; set; }
        public Nullable<int> PART_TYPEID_14 { get; set; }
        public Nullable<int> PART_TYPEID_15 { get; set; }
        public Nullable<int> PART_TYPEID_16 { get; set; }
        public Nullable<int> PART_TYPEID_17 { get; set; }
        public Nullable<int> PART_TYPEID_18 { get; set; }
        public Nullable<int> PART_TYPEID_19 { get; set; }
        public Nullable<int> PART_TYPEID_20 { get; set; }
        public Nullable<int> PART_TYPEID_21 { get; set; }
        public Nullable<int> PART_TYPEID_22 { get; set; }
        public Nullable<int> PART_TYPEID_23 { get; set; }
        public Nullable<int> PART_TYPEID_24 { get; set; }
        public Nullable<int> PART_IDX_1 { get; set; }
        public Nullable<int> PART_IDX_2 { get; set; }
        public Nullable<int> PART_IDX_3 { get; set; }
        public Nullable<int> PART_IDX_4 { get; set; }
        public Nullable<int> PART_IDX_5 { get; set; }
        public Nullable<int> PART_IDX_6 { get; set; }
        public Nullable<int> PART_IDX_7 { get; set; }
        public Nullable<int> PART_IDX_8 { get; set; }
        public Nullable<int> PART_IDX_9 { get; set; }
        public Nullable<int> PART_IDX_10 { get; set; }
        public Nullable<int> PART_IDX_11 { get; set; }
        public Nullable<int> PART_IDX_12 { get; set; }
        public Nullable<int> PART_IDX_13 { get; set; }
        public Nullable<int> PART_IDX_14 { get; set; }
        public Nullable<int> PART_IDX_15 { get; set; }
        public Nullable<int> PART_IDX_16 { get; set; }
        public Nullable<int> PART_IDX_17 { get; set; }
        public Nullable<int> PART_IDX_18 { get; set; }
        public Nullable<int> PART_IDX_19 { get; set; }
        public Nullable<int> PART_IDX_20 { get; set; }
        public Nullable<int> PART_IDX_21 { get; set; }
        public Nullable<int> PART_IDX_22 { get; set; }
        public Nullable<int> PART_IDX_23 { get; set; }
        public Nullable<int> PART_IDX_24 { get; set; }
    }
}
