//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pangya_DataConnector.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PangyaEntities : DbContext
    {
        public PangyaEntities()
            : base("name=PangyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pangya_Member> Pangya_Member { get; set; }
        public virtual DbSet<Pangya_Game_Macro> Pangya_Game_Macro { get; set; }
        public virtual DbSet<Pangya_User_Statistics> Pangya_User_Statistics { get; set; }
        public virtual DbSet<Pangya_Warehouse> Pangya_Warehouse { get; set; }
        public virtual DbSet<Pangya_Server> Pangya_Server { get; set; }
        public virtual DbSet<Pangya_Character_Equip> Pangya_Character_Equip { get; set; }
        public virtual DbSet<Pangya_Character> Pangya_Character { get; set; }
        public virtual DbSet<Pangya_User_Equip> Pangya_User_Equip { get; set; }
        public virtual DbSet<Pangya_Personal> Pangya_Personal { get; set; }
    
        public virtual ObjectResult<ProcGetGameServer_Result> ProcGetGameServer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGetGameServer_Result>("ProcGetGameServer");
        }
    
        public virtual ObjectResult<ProcGetMessengerServer_Result> ProcGetMessengerServer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGetMessengerServer_Result>("ProcGetMessengerServer");
        }
    
        public virtual ObjectResult<Nullable<byte>> USP_FIRST_CREATION(Nullable<int> uID, Nullable<int> cHAR_TYPEID, Nullable<byte> hAIRCOLOUR, string nICKNAME)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            var cHAR_TYPEIDParameter = cHAR_TYPEID.HasValue ?
                new ObjectParameter("CHAR_TYPEID", cHAR_TYPEID) :
                new ObjectParameter("CHAR_TYPEID", typeof(int));
    
            var hAIRCOLOURParameter = hAIRCOLOUR.HasValue ?
                new ObjectParameter("HAIRCOLOUR", hAIRCOLOUR) :
                new ObjectParameter("HAIRCOLOUR", typeof(byte));
    
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<byte>>("USP_FIRST_CREATION", uIDParameter, cHAR_TYPEIDParameter, hAIRCOLOURParameter, nICKNAMEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_NICKNAME_CHECK(string nICKNAME)
        {
            var nICKNAMEParameter = nICKNAME != null ?
                new ObjectParameter("NICKNAME", nICKNAME) :
                new ObjectParameter("NICKNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_NICKNAME_CHECK", nICKNAMEParameter);
        }
    
        public virtual ObjectResult<ProcGetItemWarehouse_Result> ProcGetItemWarehouse(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGetItemWarehouse_Result>("ProcGetItemWarehouse", uIDParameter);
        }
    
        public virtual ObjectResult<ProcGetToolbar_Result> ProcGetToolbar(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGetToolbar_Result>("ProcGetToolbar", uIDParameter);
        }
    
        public virtual ObjectResult<ProcGetCaddies_Result> ProcGetCaddies(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGetCaddies_Result>("ProcGetCaddies", uIDParameter);
        }
    
        public virtual ObjectResult<ProcGetCard_Result> ProcGetCard(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGetCard_Result>("ProcGetCard", uIDParameter);
        }
    
        public virtual ObjectResult<ProcGetCharacter_Result> ProcGetCharacter(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGetCharacter_Result>("ProcGetCharacter", uIDParameter);
        }
    
        public virtual ObjectResult<ProcGetMascot_Result> ProcGetMascot(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGetMascot_Result>("ProcGetMascot", uIDParameter);
        }
    
        public virtual ObjectResult<ProcGet_UserInfo_Result> ProcGet_UserInfo(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGet_UserInfo_Result>("ProcGet_UserInfo", uIDParameter);
        }
    
        public virtual ObjectResult<ProcGuildGetPlayerData_Result> ProcGuildGetPlayerData(Nullable<int> uID, Nullable<int> gUILDID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            var gUILDIDParameter = gUILDID.HasValue ?
                new ObjectParameter("GUILDID", gUILDID) :
                new ObjectParameter("GUILDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcGuildGetPlayerData_Result>("ProcGuildGetPlayerData", uIDParameter, gUILDIDParameter);
        }
    
        public virtual ObjectResult<USP_GAME_LOGIN_Result> USP_GAME_LOGIN(string uSERID, Nullable<int> uID, string code1, string code2)
        {
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));
    
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            var code1Parameter = code1 != null ?
                new ObjectParameter("Code1", code1) :
                new ObjectParameter("Code1", typeof(string));
    
            var code2Parameter = code2 != null ?
                new ObjectParameter("Code2", code2) :
                new ObjectParameter("Code2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GAME_LOGIN_Result>("USP_GAME_LOGIN", uSERIDParameter, uIDParameter, code1Parameter, code2Parameter);
        }
    }
}
